//! SQLite profile, password, recovery, and bootstrap persistence.

use std::time::Duration;

use chrono::{DateTime, Utc};
use serde::Serialize;
use serde_json::{json, value::RawValue};
use sqlx::{FromRow, Row, Sqlite, Transaction};
use uuid::Uuid;

use crate::domain::ConsoleSessionPurpose;

use super::super::super::{
    auth::{ConsoleProfile, SessionUser, TemporaryPasswordCreated},
    error::RepositoryError,
    records::DEFAULT_ADMIN_GROUP_ID,
};
use super::super::SqliteDecimal;
use super::{SqliteAuthRepository, canonical_email, parse_role, timestamp_text};

impl SqliteAuthRepository {
    pub async fn profile(&self, user_id: Uuid) -> Result<Option<ConsoleProfile>, RepositoryError> {
        select_profile(&self.pool, user_id).await
    }

    pub async fn update_display_name(
        &self,
        user_id: Uuid,
        display_name: &str,
    ) -> Result<Option<ConsoleProfile>, RepositoryError> {
        let mut transaction = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let updated =
            sqlx::query("UPDATE users SET display_name=?2 WHERE id=?1 AND status='active'")
                .bind(user_id)
                .bind(display_name)
                .execute(&mut *transaction)
                .await?;
        if updated.rows_affected() == 0 {
            transaction.rollback().await?;
            return Ok(None);
        }
        let profile = select_profile(&mut *transaction, user_id)
            .await?
            .ok_or(RepositoryError::NotFound)?;
        transaction.commit().await?;
        Ok(Some(profile))
    }

    pub async fn change_password(
        &self,
        user_id: Uuid,
        password_hash: &str,
    ) -> Result<bool, RepositoryError> {
        let mut transaction = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let now = timestamp_text(Utc::now());
        let changed = sqlx::query(
            "UPDATE users \
             SET password_hash=?2,password_changed_at=?3,auth_version=auth_version+1, \
                 password_change_required=0,temporary_password_issued_at=NULL, \
                 temporary_password_expires_at=NULL \
             WHERE id=?1 AND status='active' AND password_change_required=0",
        )
        .bind(user_id)
        .bind(password_hash)
        .bind(&now)
        .execute(&mut *transaction)
        .await?;
        if changed.rows_affected() == 0 {
            transaction.rollback().await?;
            return Ok(false);
        }
        revoke_live_sessions(&mut transaction, user_id, &now).await?;
        transaction.commit().await?;
        Ok(true)
    }

    /// Replaces an active user's Console password with an expiring,
    /// administrator-issued temporary password. The plaintext is generated by
    /// the application layer and never reaches persistence.
    pub async fn issue_temporary_password(
        &self,
        actor_user_id: Uuid,
        actor_auth_version: i64,
        user_id: Uuid,
        password_hash: &str,
        temporary_password_ttl: Duration,
    ) -> Result<TemporaryPasswordCreated, RepositoryError> {
        if actor_user_id == user_id {
            return Err(RepositoryError::CannotResetSelf);
        }
        let mut transaction = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let actor_is_current_admin = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS( \
                SELECT 1 FROM users \
                WHERE id=?1 AND auth_version=?2 AND status='active' AND role='admin' \
                  AND password_change_required=0 AND deleted_at IS NULL \
            )",
        )
        .bind(actor_user_id)
        .bind(actor_auth_version)
        .fetch_one(&mut *transaction)
        .await?;
        if !actor_is_current_admin {
            transaction.rollback().await?;
            return Err(RepositoryError::NotFound);
        }

        let target = sqlx::query_as::<_, TemporaryPasswordTarget>(
            "SELECT status,(password_hash IS NOT NULL) AS has_password,is_system,deleted_at \
             FROM users WHERE id=?1",
        )
        .bind(user_id)
        .fetch_optional(&mut *transaction)
        .await?;
        let Some(target) = target else {
            transaction.rollback().await?;
            return Err(RepositoryError::NotFound);
        };
        if target.is_system || target.deleted_at.is_some() {
            transaction.rollback().await?;
            return Err(RepositoryError::NotFound);
        }
        if target.status != "active" || !target.has_password {
            transaction.rollback().await?;
            return Err(RepositoryError::TemporaryPasswordUnavailable);
        }

        let before = user_audit(&mut transaction, user_id).await?;
        let now = Utc::now();
        let expires_at = now
            .checked_add_signed(
                chrono::Duration::from_std(temporary_password_ttl)
                    .map_err(|_| RepositoryError::Validation)?,
            )
            .ok_or(RepositoryError::Validation)?;
        let now_text = timestamp_text(now);
        sqlx::query(
            "UPDATE users SET \
             password_hash=?2,password_change_required=1, \
             temporary_password_issued_at=?3,temporary_password_expires_at=?4, \
             auth_version=auth_version+1 \
             WHERE id=?1",
        )
        .bind(user_id)
        .bind(password_hash)
        .bind(&now_text)
        .bind(timestamp_text(expires_at))
        .execute(&mut *transaction)
        .await?;
        revoke_live_sessions(&mut transaction, user_id, &now_text).await?;

        let correlation_id = Uuid::new_v4();
        let after = user_audit(&mut transaction, user_id).await?;
        insert_audit(
            &mut transaction,
            AuditInsert {
                actor_user_id: Some(actor_user_id),
                actor_type: "user",
                actor_role: Some("admin"),
                action: "issue_temporary_password",
                object_id: user_id,
                before_redacted: before,
                after_redacted: after,
                correlation_id,
            },
        )
        .await?;
        transaction.commit().await?;
        Ok(TemporaryPasswordCreated {
            user_id,
            expires_at,
            correlation_id,
        })
    }

    /// Replaces a temporary password with the user's chosen permanent
    /// password and revokes every password-change Session.
    pub async fn complete_temporary_password(
        &self,
        user_id: Uuid,
        session_id: Uuid,
        expected_auth_version: i64,
        password_hash: &str,
    ) -> Result<Option<SessionUser>, RepositoryError> {
        let mut transaction = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let now = Utc::now();
        let user = sqlx::query_as::<_, TemporaryPasswordCompletionUser>(
            "SELECT u.email,u.display_name,u.role,u.status,u.auth_version, \
                    u.password_change_required,u.temporary_password_expires_at, \
                    s.purpose AS session_purpose,s.expires_at AS session_expires_at, \
                    s.revoked_at AS session_revoked_at \
             FROM users AS u \
             JOIN user_sessions AS s ON s.user_id=u.id \
             WHERE u.id=?1 AND s.id=?2",
        )
        .bind(user_id)
        .bind(session_id)
        .fetch_optional(&mut *transaction)
        .await?;
        let Some(user) = user else {
            transaction.rollback().await?;
            return Ok(None);
        };
        let session_purpose = ConsoleSessionPurpose::parse(&user.session_purpose)
            .ok_or(RepositoryError::Validation)?;
        if user.status != "active"
            || user.auth_version != expected_auth_version
            || !user.password_change_required
            || user
                .temporary_password_expires_at
                .is_none_or(|expiry| expiry <= now)
            || session_purpose != ConsoleSessionPurpose::PasswordChange
            || user.session_revoked_at.is_some()
            || user.session_expires_at <= now
        {
            transaction.rollback().await?;
            return Ok(None);
        }
        let role = parse_role(&user.role)?;
        let before = user_audit(&mut transaction, user_id).await?;
        let now_text = timestamp_text(now);
        let auth_version = sqlx::query_scalar::<_, i64>(
            "UPDATE users SET \
             password_hash=?2,password_changed_at=?3,auth_version=auth_version+1, \
             password_change_required=0,temporary_password_issued_at=NULL, \
             temporary_password_expires_at=NULL \
             WHERE id=?1 AND auth_version=?4 RETURNING auth_version",
        )
        .bind(user_id)
        .bind(password_hash)
        .bind(&now_text)
        .bind(expected_auth_version)
        .fetch_optional(&mut *transaction)
        .await?;
        let Some(auth_version) = auth_version else {
            transaction.rollback().await?;
            return Ok(None);
        };
        revoke_live_sessions(&mut transaction, user_id, &now_text).await?;
        let after = user_audit(&mut transaction, user_id).await?;
        insert_audit(
            &mut transaction,
            AuditInsert {
                actor_user_id: Some(user_id),
                actor_type: "user",
                actor_role: Some(&user.role),
                action: "complete_password_reset",
                object_id: user_id,
                before_redacted: before,
                after_redacted: after,
                correlation_id: Uuid::new_v4(),
            },
        )
        .await?;
        transaction.commit().await?;
        Ok(Some(SessionUser {
            id: user_id,
            email: user.email,
            display_name: user.display_name,
            role,
            auth_version,
            session_purpose: ConsoleSessionPurpose::Normal,
            temporary_password_expires_at: None,
        }))
    }

    /// Emergency operator recovery for an active Console administrator.
    pub async fn reset_active_admin_password(
        &self,
        email: &str,
        password_hash: &str,
    ) -> Result<bool, RepositoryError> {
        let mut transaction = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let now = timestamp_text(Utc::now());
        let admin = sqlx::query_as::<_, PasswordResetAdmin>(
            "UPDATE users \
             SET password_hash=?2,password_changed_at=?3,auth_version=auth_version+1, \
                 password_change_required=0,temporary_password_issued_at=NULL, \
                 temporary_password_expires_at=NULL \
             WHERE email=?1 AND role='admin' AND status='active' \
             RETURNING id,email,auth_version",
        )
        .bind(canonical_email(email))
        .bind(password_hash)
        .bind(&now)
        .fetch_optional(&mut *transaction)
        .await?;
        let Some(admin) = admin else {
            transaction.rollback().await?;
            return Ok(false);
        };
        revoke_live_sessions(&mut transaction, admin.id, &now).await?;
        insert_audit(
            &mut transaction,
            AuditInsert {
                actor_user_id: None,
                actor_type: "system",
                actor_role: None,
                action: "reset_password",
                object_id: admin.id,
                before_redacted: serde_json::to_string(&json!({
                    "email": admin.email.clone(),
                    "role": "admin",
                    "status": "active",
                }))
                .map_err(|_| RepositoryError::Validation)?,
                after_redacted: serde_json::to_string(&json!({
                    "email": admin.email,
                    "role": "admin",
                    "status": "active",
                    "auth_version": admin.auth_version,
                    "password_changed": true,
                }))
                .map_err(|_| RepositoryError::Validation)?,
                correlation_id: Uuid::new_v4(),
            },
        )
        .await?;
        transaction.commit().await?;
        Ok(true)
    }

    pub async fn bootstrap_admin(
        &self,
        email: &str,
        display_name: &str,
        password_hash: &str,
    ) -> Result<Uuid, RepositoryError> {
        let mut transaction = self.pool.begin_with("BEGIN IMMEDIATE").await?;
        let exists = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS(SELECT 1 FROM users WHERE status='active' AND role='admin')",
        )
        .fetch_one(&mut *transaction)
        .await?;
        if exists {
            transaction.rollback().await?;
            return Err(RepositoryError::Conflict);
        }
        if email.trim().is_empty() || display_name.trim().is_empty() || password_hash.is_empty() {
            transaction.rollback().await?;
            return Err(RepositoryError::Validation);
        }
        let id = Uuid::new_v4();
        let email = canonical_email(email);
        let now = timestamp_text(Utc::now());
        sqlx::query(
            "INSERT INTO users \
             (id,email,display_name,role,status,password_hash,password_changed_at,user_group_id) \
             VALUES (?1,?2,?3,'admin','active',?4,?5,?6)",
        )
        .bind(id)
        .bind(&email)
        .bind(display_name)
        .bind(password_hash)
        .bind(&now)
        .bind(DEFAULT_ADMIN_GROUP_ID)
        .execute(&mut *transaction)
        .await?;
        insert_audit(
            &mut transaction,
            AuditInsert {
                actor_user_id: None,
                actor_type: "system",
                actor_role: None,
                action: "bootstrap",
                object_id: id,
                before_redacted: "{}".to_owned(),
                after_redacted: serde_json::to_string(&json!({
                    "id": id,
                    "email": email,
                    "display_name": display_name,
                    "role": "admin",
                    "status": "active",
                }))
                .map_err(|_| RepositoryError::Validation)?,
                correlation_id: Uuid::new_v4(),
            },
        )
        .await?;
        transaction.commit().await?;
        Ok(id)
    }
}

async fn select_profile<'e, E>(
    executor: E,
    user_id: Uuid,
) -> Result<Option<ConsoleProfile>, RepositoryError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    sqlx::query_as::<_, ConsoleProfile>(
        "SELECT id,email,display_name,role,status,balance_amount,created_at,updated_at \
         FROM users WHERE id=?1",
    )
    .bind(user_id)
    .fetch_optional(executor)
    .await
    .map_err(RepositoryError::from)
}

async fn revoke_live_sessions(
    transaction: &mut Transaction<'_, Sqlite>,
    user_id: Uuid,
    revoked_at: &str,
) -> Result<(), RepositoryError> {
    sqlx::query("UPDATE user_sessions SET revoked_at=?2 WHERE user_id=?1 AND revoked_at IS NULL")
        .bind(user_id)
        .bind(revoked_at)
        .execute(&mut **transaction)
        .await?;
    Ok(())
}

async fn user_audit(
    transaction: &mut Transaction<'_, Sqlite>,
    id: Uuid,
) -> Result<String, RepositoryError> {
    let row = sqlx::query(
        "SELECT u.id,u.email,u.display_name,u.role,u.status,u.password_hash, \
                u.password_change_required,u.temporary_password_expires_at, \
                u.user_group_id,g.system_role AS user_group_system_role, \
                u.default_api_key_policy_id, \
                COALESCE(u.default_api_key_policy_id,g.default_api_key_policy_id) \
                    AS effective_api_key_policy_id, \
                u.websocket_enabled,u.balance_amount,u.deleted_at,u.deleted_by, \
                u.created_at,u.updated_at \
         FROM users AS u \
         JOIN user_groups AS g ON g.id=u.user_group_id \
         WHERE u.id=?1 AND u.is_system=0",
    )
    .bind(id)
    .fetch_optional(&mut **transaction)
    .await?
    .ok_or(RepositoryError::NotFound)?;
    let balance_amount = row
        .try_get::<SqliteDecimal, _>("balance_amount")?
        .into_inner();
    let balance_amount = RawValue::from_string(balance_amount.to_string())
        .map_err(|_| RepositoryError::Validation)?;
    let audit = UserAudit {
        id: row.try_get("id")?,
        email: row.try_get("email")?,
        display_name: row.try_get("display_name")?,
        role: row.try_get("role")?,
        status: row.try_get("status")?,
        can_reissue_invitation: row.try_get::<Option<String>, _>("password_hash")?.is_none()
            && row.try_get::<Option<String>, _>("email")?.is_some()
            && matches!(
                row.try_get::<String, _>("status")?.as_str(),
                "invited" | "suspended" | "disabled"
            ),
        password_change_required: row.try_get("password_change_required")?,
        temporary_password_expires_at: row.try_get("temporary_password_expires_at")?,
        user_group_id: row.try_get("user_group_id")?,
        user_group_system_role: row.try_get("user_group_system_role")?,
        default_api_key_policy_id: row.try_get("default_api_key_policy_id")?,
        effective_api_key_policy_id: row.try_get("effective_api_key_policy_id")?,
        websocket_enabled: row.try_get("websocket_enabled")?,
        balance_amount,
        deleted_at: row.try_get("deleted_at")?,
        deleted_by: row.try_get("deleted_by")?,
        created_at: row.try_get("created_at")?,
        updated_at: row.try_get("updated_at")?,
    };
    serde_json::to_string(&audit).map_err(|_| RepositoryError::Validation)
}

struct AuditInsert<'a> {
    actor_user_id: Option<Uuid>,
    actor_type: &'a str,
    actor_role: Option<&'a str>,
    action: &'a str,
    object_id: Uuid,
    before_redacted: String,
    after_redacted: String,
    correlation_id: Uuid,
}

async fn insert_audit(
    transaction: &mut Transaction<'_, Sqlite>,
    input: AuditInsert<'_>,
) -> Result<(), RepositoryError> {
    sqlx::query(
        "INSERT INTO audit_logs \
         (id,actor_user_id,actor_type,actor_role,action,object_type,object_id, \
          before_redacted,after_redacted,correlation_id) \
         VALUES (?1,?2,?3,?4,?5,'user',?6,?7,?8,?9)",
    )
    .bind(Uuid::new_v4())
    .bind(input.actor_user_id)
    .bind(input.actor_type)
    .bind(input.actor_role)
    .bind(input.action)
    .bind(input.object_id)
    .bind(input.before_redacted)
    .bind(input.after_redacted)
    .bind(input.correlation_id.to_string())
    .execute(&mut **transaction)
    .await?;
    Ok(())
}

#[derive(FromRow)]
struct TemporaryPasswordTarget {
    status: String,
    has_password: bool,
    is_system: bool,
    deleted_at: Option<DateTime<Utc>>,
}

#[derive(FromRow)]
struct TemporaryPasswordCompletionUser {
    email: Option<String>,
    display_name: String,
    role: String,
    status: String,
    auth_version: i64,
    password_change_required: bool,
    temporary_password_expires_at: Option<DateTime<Utc>>,
    session_purpose: String,
    session_expires_at: DateTime<Utc>,
    session_revoked_at: Option<DateTime<Utc>>,
}

#[derive(FromRow)]
struct PasswordResetAdmin {
    id: Uuid,
    email: Option<String>,
    auth_version: i64,
}

#[derive(Serialize)]
struct UserAudit {
    id: Uuid,
    email: Option<String>,
    display_name: String,
    role: String,
    status: String,
    can_reissue_invitation: bool,
    password_change_required: bool,
    temporary_password_expires_at: Option<DateTime<Utc>>,
    user_group_id: Uuid,
    user_group_system_role: Option<String>,
    default_api_key_policy_id: Option<Uuid>,
    effective_api_key_policy_id: Option<Uuid>,
    websocket_enabled: bool,
    balance_amount: Box<RawValue>,
    deleted_at: Option<DateTime<Utc>>,
    deleted_by: Option<Uuid>,
    created_at: DateTime<Utc>,
    updated_at: DateTime<Utc>,
}
